- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: sudo kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: sudo "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

# To add more workers in current cluster, run this in new worker
# Command: sudo kubeadm join 172.31.40.31:6443 --token 8nzonx.81w485emdzqiuiit \
    --discovery-token-ca-cert-hash sha256:56c1bba1187a900ac5058b2c5d3437f311b851c87e49cfedaab33393e7dae6d0
