apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userinterface
  template:
    metadata:
      labels:
        app: userinterface
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - userinterface
              topologyKey: kubernetes.io/hostname
      containers:
        - image: hp2304/vidhyapak:userinterface
          imagePullPolicy: Always
          name: userinterface
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: userinterface
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
